language: csharp
solution: TFSToolset.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore TFSToolset.sln
after_script:
  - nunit-console TFSToolset.Tests/bin/Release/Tests.dll